### ISSUE TITLE
Missing `incoming_customers` type

### ISSUE THREAD

**Issue by fjaskolski** [livechat/lc-sdk-js#119]
Hi! 

The `Push` type has `IncomingCustomers` [payload enum](https://github.com/livechat/lc-sdk-js/blob/b925a52aa50fb5430069eb6fe8a31f65f03c0680/src/agent/structures/pushes.ts#L174), but there is no type definition for its payload.

<img width="541" alt="Screen Shot 2023-05-10 at 13 17 12" src="https://github.com/livechat/lc-sdk-js/assets/5114422/3bc4b833-36e7-4dc9-af22-1bb90e3b3105">

It seems that the supposed structure for this payload is:

`
interface IncomingCustomers {
  customers: Customer[];
  customer_monitoring_level?: CustomerMonitoringLevel;
}
`

**Comment by wfabjanczuk** [comment]
It will be addressed in https://github.com/livechat/lc-sdk-js/pull/120 and following pull requests in previous versions

**Comment by wfabjanczuk** [comment]
Issue has been fixed in all non-deprecated versions (v3.3, v3.4, v3.5 and v3.6)
